
import { Product, Atmosphere } from './types';

export const ATMOSPHERES: Atmosphere[] = [
  {
    id: 'forest',
    video: 'https://assets.mixkit.co/videos/preview/mixkit-forest-stream-in-the-sunlight-529-large.mp4',
    audio: 'https://assets.mixkit.co/sfx/preview/mixkit-forest-birds-ambience-1210.mp3',
    name: 'Forêt Sacrée',
    color: 'rgba(132, 204, 22, 0.15)'
  },
  {
    id: 'water',
    video: 'https://assets.mixkit.co/videos/preview/mixkit-waterfall-in-a-forest-in-slow-motion-4861-large.mp4',
    audio: 'https://assets.mixkit.co/sfx/preview/mixkit-soft-river-water-flow-1144.mp3',
    name: 'Source de Vie',
    color: 'rgba(6, 182, 212, 0.15)'
  },
  {
    id: 'zen',
    video: 'https://assets.mixkit.co/videos/preview/mixkit-clouds-and-blue-sky-background-202-large.mp4',
    audio: 'https://assets.mixkit.co/sfx/preview/mixkit-morning-countryside-ambience-1216.mp3',
    name: 'Paix Intérieure',
    color: 'rgba(245, 158, 11, 0.15)'
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Koundjé',
    scientificName: 'Commiphora africana',
    description: 'Une plante précieuse utilisée pour la purification de l\'organisme et la protection spirituelle. Elle aide à éliminer les impuretés internes.',
    benefits: ['Détoxifiant naturel', 'Protection de l\'aura', 'Apaisement digestif'],
    usage: 'En infusion légère le soir ou en bain de vapeur.',
    origin: 'Afrique de l\'Ouest',
    category: 'Roots',
    price: '14,50€',
    virtues: ['Bain de Purification', 'Protection Totale'],
    symptoms: ['Lourdeurs digestives', 'Stress', 'Énergies négatives'],
    image: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p12',
    name: 'Kinkeliba Royal (Fagot)',
    scientificName: 'Combretum micranthum',
    description: 'La "tisane de longue vie". Présenté en fagots traditionnels liés à l\'écorce, ce Kinkeliba sauvage est un puissant draineur hépatique.',
    benefits: ['Nettoyage du foie', 'Action antioxydante', 'Aide à la digestion'],
    usage: 'Faire bouillir un petit morceau du fagot pendant 10 min. Boire chaud ou froid.',
    origin: 'Sénégal / Mali',
    category: 'Leaves',
    price: '9,50€',
    virtues: ['Bien-être', 'Bain de Purification'],
    symptoms: ['Lendemain de fête', 'Digestion lente', 'Fatigue hépatique'],
    image: 'https://images.unsplash.com/photo-1544965838-54ef8406f868?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p13',
    name: 'Gowé de Kayes (Boules)',
    scientificName: 'Cyperus rotundus',
    description: 'Boules de racines odorantes tressées. Utilisées depuis la nuit des temps pour la purification interne et le parfumage naturel du corps.',
    benefits: ['Antibactérien naturel', 'Parfum corporel', 'Hygiène intime'],
    usage: 'À faire infuser ou à brûler comme encens purificateur.',
    origin: 'Région de Kayes',
    category: 'Roots',
    price: '18,00€',
    virtues: ['Bain de Purification', 'Harmonie & Couple'],
    symptoms: ['Odeurs corporelles', 'Besoin de purification', 'Inconfort intime'],
    image: 'https://images.unsplash.com/photo-1564043721511-2f7b4caef58e?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p14',
    name: 'Khamaré (Faisceau de Racines)',
    scientificName: 'Vetiveria zizanioides',
    description: 'Racines de vétiver présentées en faisceaux. Indispensable pour l\'équilibre et la vitalité, apporte une fraîcheur incomparable.',
    benefits: ['Équilibre hormonal', 'Teint lumineux', 'Soin post-partum'],
    usage: 'Placer une tige dans une bouteille d\'eau, laisser infuser et boire toute la journée.',
    origin: 'Mali',
    category: 'Roots',
    price: '12,50€',
    virtues: ['Bien-être', 'Harmonie & Couple'],
    symptoms: ['Règles douloureuses', 'Teint terne', 'Stress'],
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p15',
    name: 'Feuilles de Djéka',
    scientificName: 'Alchornea cordifolia',
    description: 'Fagots de feuilles larges. Reconnues pour leurs propriétés cicatrisantes et antiseptiques puissantes.',
    benefits: ['Cicatrisation rapide', 'Désinfectant', 'Soin féminin'],
    usage: 'En bain de siège ou en infusion pour les soins externes.',
    origin: 'Guinée',
    category: 'Leaves',
    price: '10,00€',
    virtues: ['Harmonie & Couple', 'Bien-être'],
    symptoms: ['Infections légères', 'Post-accouchement', 'Pertes blanches'],
    image: 'https://images.unsplash.com/photo-1622210084443-424a66e4a640?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p16',
    name: 'Citronnelle de Brousse',
    scientificName: 'Cymbopogon proximus',
    description: 'Fagots d\'herbes sèches très fines. Une plante "miracle" pour libérer les voies respiratoires et apaiser le système nerveux.',
    benefits: ['Sommeil profond', 'Dégagement bronchique', 'Sudorifique'],
    usage: 'En tisane du soir ou en inhalation sous un pagne.',
    origin: 'Sahel',
    category: 'Leaves',
    price: '7,50€',
    virtues: ['Bien-être', 'Protection Totale'],
    symptoms: ['Rhume', 'Toux', 'Anxiété avant le coucher'],
    image: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d5e?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p2',
    name: 'Sounsounfing',
    scientificName: 'Annona senegalensis',
    description: 'Reconnu pour ses propriétés contre les fièvres et les douleurs articulaires. Une plante de force pour les périodes de fatigue.',
    benefits: ['Combat la fièvre', 'Soutien articulaire', 'Regain d\'énergie'],
    usage: 'Faire bouillir les feuilles ou racines et boire tiède.',
    origin: 'Mali',
    category: 'Leaves',
    price: '12,00€',
    virtues: ['Bien-être', 'Protection Totale'],
    symptoms: ['Fièvre', 'Douleurs musculaires', 'Fatigue'],
    image: 'https://images.unsplash.com/photo-1622210084443-424a66e4a640?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p3',
    name: 'Manding Sounsoun',
    scientificName: 'Annona sp. Manding',
    description: 'Variété spécifique du pays Manding, très appréciée pour tonifier le système nerveux et améliorer la clarté mentale.',
    benefits: ['Éveil mental', 'Équilibre nerveux', 'Force intérieure'],
    usage: 'Infusion matinale pour une journée sereine.',
    origin: 'Pays Manding',
    category: 'Leaves',
    price: '13,00€',
    virtues: ['Mémoire & Examens', 'Bien-être'],
    symptoms: ['Manque de concentration', 'Anxiété', 'Nervosité'],
    image: 'https://images.unsplash.com/photo-1544965838-54ef8406f868?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p4',
    name: 'Djatigii Faga (Sérénidje)',
    scientificName: 'Lippia chevalieri',
    description: 'La plante de la paix et de l\'hospitalité. Idéale pour apaiser les tensions au sein du foyer et favoriser le sommeil profond.',
    benefits: ['Sommeil réparateur', 'Harmonie familiale', 'Calme le cœur'],
    usage: 'En infusion avant le coucher ou en parfum d\'intérieur.',
    origin: 'Guinée / Mali',
    category: 'Leaves',
    price: '16,50€',
    virtues: ['Harmonie & Couple', 'Bien-être'],
    symptoms: ['Insomnie', 'Tensions relationnelles', 'Palpitations'],
    image: 'https://images.unsplash.com/photo-1502338100291-112201b72239?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p5',
    name: 'Timi Timini',
    scientificName: 'Scoparia dulcis',
    description: 'Plante "douce" par excellence, très utilisée pour les enfants et pour apaiser les irritations de la gorge.',
    benefits: ['Adoucissant respiratoire', 'Soin des enfants', 'Régulateur thermique'],
    usage: 'Infuser une petite poignée dans de l\'eau tiède.',
    origin: 'Bénin',
    category: 'Leaves',
    price: '9,00€',
    virtues: ['Bien-être'],
    symptoms: ['Toux sèche', 'Chaleur interne', 'Irritations'],
    image: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d5e?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p6',
    name: 'Aladjon',
    scientificName: 'Cassia sieberiana',
    description: 'Plante herculéenne de la pharmacopée africaine. Elle est le remède universel pour fortifier le sang et les os.',
    benefits: ['Tonique sanguin', 'Renforcement osseux', 'Vitalité globale'],
    usage: 'Décoction de racines à boire en cure de 7 jours.',
    origin: 'Sénégal',
    category: 'Roots',
    price: '18,00€',
    virtues: ['Bien-être', 'Ouverture & Succes'],
    symptoms: ['Anémie', 'Faiblesse physique', 'Récupération'],
    image: 'https://imgur.com/JUlsfiA.jpeg',
    stock: 50
  },
  {
    id: 'p7',
    name: 'Diala',
    scientificName: 'Khaya senegalensis',
    description: 'L\'Acajou d\'Afrique. Son écorce amère est légendaire pour combattre les fièvres tenaces et purifier le foie.',
    benefits: ['Anti-paludéen traditionnel', 'Purifiant hépatique', 'Antiseptique'],
    usage: 'Faire bouillir un morceau d\'écorce, boire un petit verre (très amer).',
    origin: 'Zone Sahélienne',
    category: 'Roots',
    price: '21,00€',
    virtues: ['Bain de Purification', 'Protection Totale'],
    symptoms: ['Fièvre tropicale', 'Problèmes de foie', 'Infections'],
    image: 'https://images.unsplash.com/photo-1605333396915-47ed6b68a00e?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p8',
    name: 'Ngokou',
    scientificName: 'Terminalia macroptera',
    description: 'Utilisé pour soigner les maux de ventre profonds et les problèmes respiratoires chroniques.',
    benefits: ['Santé intestinale', 'Dégagement des bronches', 'Anti-inflammatoire'],
    usage: 'Consommer en décoction longue.',
    origin: 'Burkina Faso',
    category: 'Roots',
    price: '15,00€',
    virtues: ['Bien-être'],
    symptoms: ['Maux de ventre', 'Bronchite', 'Inflammations'],
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p9',
    name: 'Kolokolo',
    scientificName: 'Pericopsis laxiflora',
    description: 'Une plante de "refroidissement" utilisée pour apaiser les inflammations cutanées et les brûlures internes.',
    benefits: ['Apaisement cutané', 'Rafraîchit le corps', 'Cicatrisation'],
    usage: 'Utiliser en lotion sur la peau ou en boisson fraîche.',
    origin: 'Côte d\'Ivoire',
    category: 'Leaves',
    price: '11,50€',
    virtues: ['Bien-être', 'Bain de Purification'],
    symptoms: ['Eruptions cutanées', 'Excès de chaleur', 'Irritations'],
    image: 'https://images.unsplash.com/photo-1564043721511-2f7b4caef58e?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p10',
    name: 'Minzé',
    scientificName: 'Mentha africana',
    description: 'La menthe sauvage africaine. Puissante et parfumée, elle facilite la digestion et rafraîchit l\'esprit.',
    benefits: ['Digestion facile', 'Haleine fraîche', 'Stimulant léger'],
    usage: 'Infusion après le repas.',
    origin: 'Mali',
    category: 'Leaves',
    price: '8,50€',
    virtues: ['Bien-être'],
    symptoms: ['Ballonnements', 'Digestion difficile', 'Fatigue mentale'],
    image: 'https://images.unsplash.com/photo-1533221216134-530091411322?q=80&w=800&auto=format&fit=crop',
    stock: 50
  },
  {
    id: 'p11',
    name: 'Kalakaridjé',
    scientificName: 'Hymenocardia acida',
    description: 'Reconnue pour ses vertus tonifiantes et sa capacité à renforcer la virilité et la résistance physique.',
    benefits: ['Force masculine', 'Endurance', 'Vitalité'],
    usage: 'Décoction de racines, à prendre en cure.',
    origin: 'Niger',
    category: 'Roots',
    price: '24,00€',
    virtues: ['Harmonie & Couple', 'Ouverture & Succes'],
    symptoms: ['Baisse de régime', 'Faiblesse sexuelle', 'Manque d\'endurance'],
    image: 'https://images.unsplash.com/photo-1544253102-390b1442f4c4?q=80&w=800&auto=format&fit=crop',
    stock: 50
  }
];
